#pragma once
#ifndef __CTPDEFS_H__
#define __CTPDEFS_H__

//md
#define MDONFRONTCONNECTED "MDONFRONTCONNECTED_CTP"
#define MDONFRONTDISCONNECTED "MDONFRONTDISCONNECTED_CTP"
#define MDONHEARTBEATWARNING "MDONHEARTBEATWARNING_CTP"
#define MDONRSPUSERLOGIN "MDONRSPUSERLOGIN_CTP"
#define MDONRSPUSERLOGOUT "MDONRSPUSERLOGOUT_CTP"
#define MDONRSPERROR "MDONRSPERROR_CTP"
#define MDONRSPSUBMARKETDATA "MDONRSPSUBMARKETDATA_CTP"
#define MDONRSPUNSUBMARKETDATA "MDONRSPUNSUBMARKETDATA_CTP"
#define MDONRSPSUBFORQUOTERSP "MDONRSPSUBFORQUOTERSP"
#define MDONRSPUNSUBFORQUOTERSP "MDONRSPUNSUBFORQUOTERSP_CTP"
#define MDONRTNDEPTHMARKETDATA "MDONRTNDEPTHMARKETDATA_CTP"
#define MDONRTNFORQUOTERSP "MDONRTNFORQUOTERSP_CTP"

//td
#define TDONFRONTCONNECTED "TDONFRONTCONNECTED_CTP"
#define TDONFRONTDISCONNECTED "TDONFRONTDISCONNECTED_CTP"
#define TDONRSPUSERLOGIN "TDONRSPUSERLOGIN_CTP"
#define TDONRSPUSERLOGOUT "TDONRSPUSERLOGOUT_CTP"
#define TDONRSPORDERINSERT "TDONRSPORDERINSERT_CTP"
#define TDONRSPORDERACTION "TDONRSPORDERACTION_CTP"
#define TDONRSPSETTLEMENTINFOCONFIRM "TDONRSPSETTLEMENTINFOCONFIRM_CTP"
#define TDONRSPQRYINVESTORPOSITION "TDONRSPQRYINVESTORPOSITION_CTP"
#define TDONRSPQRYTRADINGACCOUNT "TDONRSPQRYTRADINGACCOUNT_CTP"
#define TDONRSPQRYINSTRUMENT "TDONRSPQRYINSTRUMENT_CTP"
#define TDONRSPERROR "TDONRSPERROR_CTP"
#define TDONRTNORDER "TDONRTNORDER_CTP"
#define TDONRTNTRADE "TDONRTNTRADE_CTP"
#define TDONERRRTNORDERINSERT "TDONERRRTNORDERINSERT_CTP"
#define TDONERRRTNORDERACTION "TDONERRRTNORDERACTION_CTP"

#endif
